### ISSUE TITLE
error trying to build 

### ISSUE THREAD

**Issue by afhuertass** [arbox/shalmaneser#5]
Hi ! 

I'm tying to use this programm for an aunt that is making a master dregree in some topics of traducction and other things but she has no background in programming. 

But i'm stuck with this error when i try to run : rake build:shalmaneser

bundle exec gem build shalmaneser-rosy.gemspec
Invalid gemspec in [shalmaneser-rosy.gemspec]: cannot load such file -- common/definitions
ERROR:  Error loading gemspec. Aborting.
rake aborted!
Command failed with status (1): [bundle exec gem build shalmaneser-rosy.gem...]
/home/andresh/shalmaneser/Rakefile:208:in `block (2 levels) in <top (required)>'
Tasks: TOP => build:shalmaneser => build:rosy
(See full trace by running task with --trace)
 

there is no common/definitions folder.. and i dont know what to do or what i'm doing wrong. 

Thanks, any help is appreciated

**Comment by arbox** [comment]
I'll look at it.
Shalmaneser is still unstable. How did you come across it? What are you planning to accomplish with Shalmaneser?

**Comment by afhuertass** [comment]
Hi. 

an aunt need it to get the frames for some text, she is doing a master degree in traducction or something like that, but has  no background in programming so she ask me for help, but i'm not making any progress yet.

Going into the .gemspec and commenting the line with the ruby version, i was able to compile the gems using rake, then i installed ( gem install blabla.gem )  an i can use in my console fred and shalmaneser , but if i try to user rosy i get this ; 

Rosy cannot serve you!
uninitialized constant Rosy
/usr/local/lib/ruby/gems/2.2.0/gems/shalmaneser-rosy-1.2/lib/rosy/opt_parser.rb:205:in `help'
/usr/local/lib/ruby/gems/2.2.0/gems/shalmaneser-rosy-1.2/lib/rosy/opt_parser.rb:131:in `parse'
/usr/local/lib/ruby/gems/2.2.0/gems/shalmaneser-rosy-1.2/bin/rosy:15:in `<top (required)>'
/usr/local/bin/rosy:23:in `load'
/usr/local/bin/rosy:23:in `<main>'

and for frappe 

/usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- salsa_tiger_xml/corpus (LoadError)
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shalmaneser-1.2/lib/frappe/frappe_helper.rb:9:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shalmaneser-1.2/lib/frappe/frappe.rb:2:in `require_relative'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shalmaneser-1.2/lib/frappe/frappe.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/gems/2.2.0/gems/shalmaneser-1.2/bin/frappe:25:in `<top (required)>'
	from /usr/local/bin/frappe:23:in `load'
	from /usr/local/bin/frappe:23:in `<main>'


any clue or suggestion? thanks .

**Comment by afhuertass** [comment]
Hi ! me again :p 

i'm getting some more positive messages, frappe dont explode when i try to use it, but i'm not able to tagg correctly the input. I have a experiment file and when i run the frappe -e file   ,everything seems to work well ( no errors) but the output ( .xml ) is empty . i think that is because the experiment file is not correctly pointing to the location of my tagger. i have the tagger(treetagger) in mi home directory, and atfer follow the instalation steps and run the example ( "echo 'Hello world!' | cmd/tree-tagger-english ") it works, but dont work with frappe :(  what is the file i should point in the  pos_tagger_path and the lemmatizer_path ? 

Thanks for your time and answers :)

**Comment by arbox** [comment]
Please be patient, I'm working on it. Shalmaneser is rather complex.
If you want a quick solution please take the Semafor parser with trained classifiers. It could be a better solution for now if your colleague wants only simple results on English texts.

**Comment by afhuertass** [comment]
thanks . 

I would gladly use that semafor parser, but all the links  (https://github.com/Noahs-ARK/semafor) to the required stuff seems to be broken.

**Comment by arbox** [comment]
Please try to install the latest version via RubyGems. It should work.

**Comment by afhuertass** [comment]
Hi , it work dont work either,  https://rubygems.org/gems/shalmaneser/versions/1.2.0.rc4 

because i have ruby 2.2.0 , and when i try to install it, says i need the version 2.0 

grettins.
